# nixpacks.toml - LANGKAH 1
[phases.setup]
packages = ["php82", "composer"]

[phases.install]
cmds = ["composer install --ignore-platform-reqs"]

[start]
cmd = "echo 'Composer install finished, container is alive.' && sleep 3600"